name: Label Merge Conflict

on:
  pull_request:
    branches:
    - master

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
    - name: Label Conflicting Pull Requests
      uses: eps1lon/actions-label-merge-conflict@v2.0.0