# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate README 파일

on:
  push:
    branches: [ blog ]
#  pull_request:
#    branches: [ blog ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
    - name: Run maintenance.py
      run: |
        python scripts/maintenance.py -g
    - name: Create commits
      run: |
          git config user.name 'kenshin579'
          git config user.email 'kenshin579@hotmail.com'
          git add README.md
          git commit -am "update README file"
#          git push
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update README file
        committer: kenshin579@
        branch: readme-patches
        delete-branch: true
        title: '[AUTO] Update README file'
        body: |
          Update README file
        labels: |
          automated pr
        assignees: kenshin579
        reviewers: kenshin579
