# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate README 파일

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
    - name: Run maintenance.py
      run: |
        python scripts/maintenance.py -g
    - name: Commit README file
      run: |
        git config --local user.email "kenshin579@hotmail.com"
        git config --local user.name "kenshin579"
        git commit -m "update generated README" -a
    - name: Push changes
        uses: ad-m/github-push-action@master